### ISSUE TITLE
NPE at net.sf.saxon.s9api.ItemTypeFactory.getElementTest when -config specified

### ISSUE THREAD

**Issue by AirQuick** [cfoster/saxon-jing#4]
On 0.9.1, with `-config` command line, Saxon-EE 9.7.0.14 terminates even before displaying the help message.
This didn't happen on 0.9.0.

```
>java -cp jing-20091111.jar;saxon9ee.jar;saxon-jing-0.9.1.jar net.sf.saxon.Transform -init:net.cfoster.saxonjing.JingInitializer -config:config.xml
java.lang.NullPointerException
        at net.sf.saxon.s9api.ItemTypeFactory.getElementTest(ItemTypeFactory.java:345)
        at net.cfoster.saxonjing.SchemaReportFunction.<init>(SchemaReportFunction.java:42)
        at net.cfoster.saxonjing.JingInitializer.initialize(JingInitializer.java:29)
        at net.sf.saxon.trans.CommandLineOptions.applyToConfiguration(CommandLineOptions.java:451)
        at net.sf.saxon.Transform.doTransform(Transform.java:334)
        at net.sf.saxon.Transform.main(Transform.java:77)
Fatal error during transformation: java.lang.NullPointerException:  (no message)
```

Here's `config.xml`. (though its content doesn't seem to matter)

```xml
<?xml version="1.0"?>
<configuration edition="EE" xmlns="http://saxon.sf.net/ns/configuration">
	<global expandAttributeDefaults="false" />
</configuration>
```

**Comment by AirQuick** [comment]
repro with Saxon-EE 9.7.0.7 too

**Comment by cfoster** [comment]
@AirQuick I've created a patch jar at http://www.cfoster.net/zip/saxon-jing-0.9.1a.jar

If this works for you, please let me know and I'll release saxon-jing-0.9.2.zip

If something else goes wrong on your development journey, please raise another ticket.

**Comment by AirQuick** [comment]
Thanks! The reported problem gone away.
