### ISSUE TITLE
Errors in oXygen v. 22

### ISSUE THREAD

**Issue by Arithmeticus** [cfoster/saxon-jing#6]
In oXygen version 22, an error is thrown on an XSLT stylesheet that is configured to a transformation scenario that invokes Saxon-Jing: **net.sf.saxon.Configuration.getProcessor()Ljava/lang/Object;**

The error happens specifically when setting the Initializer to the class: net.cfoster.saxonjing.Jinginitializer

oXygen version 21 is fine, and has as default Saxon HE/PE/EE 9.8.0.12. oXygen version 22 is running Saxon 9.9.1.5.

Seems like something in Saxon 9.9 doesn't square with saxon-jing.

**Comment by Arithmeticus** [comment]
@cfoster Just in case this issue is being monitored, here is a sample trace message for the error reported above:
```
Exception in thread "main" java.lang.NoSuchMethodError: net.sf.saxon.Configuration.getProcessor()Ljava/lang/Object;
        at net.cfoster.saxonjing.JingInitializer.initialize(JingInitializer.java:28)
        at net.sf.saxon.trans.CommandLineOptions.applyToConfiguration(CommandLineOptions.java:494)
        at net.sf.saxon.Transform.doTransform(Transform.java:342)
        at net.sf.saxon.Transform.main(Transform.java:80)
```
It seems related to changes in [Saxon 9.9 forward](https://www.saxonica.com/documentation9.9/index.html#!changes) 

_The class Serializer is no longer available as a free standing class, it must be created using the Processor class. The return type of the method Serializer.GetOutputDestination() has been changed to object. This class has a number of serialization parameters available for use by the Serializer. The BaseUri property allows the setting and getting of the base Uri for the Serializer_
